stages:
  - build
  - dockerize
  - deploy

image: node:lts-alpine
services:
  - docker:dind

gateway-build:
  stage: build
  script:
    - yarn
    - yarn build gateway
  artifacts:
    paths:
      - dist/apps/gateway

customer-build:
  stage: build
  script:
    - yarn
    - yarn build customer
  artifacts:
    paths:
      - dist/apps/customer

auth-build:
  stage: build
  script:
    - yarn
    - yarn build auth
  artifacts:
    paths:
      - dist/apps/auth

gateway-dockerize:
  image: docker:latest
  stage: dockerize
  script:
    - docker build -t gateway --build-arg microservice=gateway .

customer-dockerize:
  image: docker:latest
  stage: dockerize
  script:
    - docker build -t customer --build-arg microservice=customer .

auth-dockerize:
  image: docker:latest
  stage: dockerize
  script:
    - docker build -t auth --build-arg microservice=auth .
