apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deploy
  template:
    metadata:
      labels:
        app: gateway-deploy
    spec:
      containers:
        - name: gateway-deploy
          image: registry.gitlab.com/yasharhtml_stud/nestjs_banking/gateway
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          env:
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  key: FIREBASE-CLIENT-EMAIL
                  name: firebase-secret
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: FIREBASE-PRIVATE-KEY
                  name: firebase-secret
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: FIREBASE-PROJECT-ID
                  name: firebase-secret
            
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE-SECRET-KEY
                  name: stripe-secret
            - name: STRIPE_API_VERSION
              valueFrom:
                secretKeyRef:
                  key: STRIPE-API-VERSION
                  name: stripe-secret
            
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  key: NATS-URL
                  name: nats-config-map
                
